# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HandlingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=5, max_digits=8)),
                ('width', models.DecimalField(decimal_places=5, max_digits=8)),
                ('height', models.DecimalField(decimal_places=5, max_digits=8)),
                ('classifications', models.ManyToManyField(to='merry.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='PointCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ColorFeature',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='merry.Feature')),
                ('color', models.CharField(max_length=20)),
            ],
            bases=('merry.feature',),
        ),
        migrations.AddField(
            model_name='object',
            name='features',
            field=models.ManyToManyField(to='merry.Feature'),
        ),
        migrations.AddField(
            model_name='object',
            name='images',
            field=models.ManyToManyField(to='merry.Image'),
        ),
        migrations.AddField(
            model_name='object',
            name='point_clouds',
            field=models.ManyToManyField(to='merry.PointCloud'),
        ),
    ]
